// 引导计划的**轻量清单** —— 生成物，不要手改。改完计划或内容跑 `npm run gen:nav`。
//
// 【为什么要有这一份，而不是让客户端去展开 content/plans】
// content/plans.ts 要 import content/nav（134 KB）和 content/nav-exercises（39 KB）
// 才能把「这门课的全部课文」这种查询展开成真实条目。而顶栏那枚计划徽标、
// 侧栏那块面板、页内那条位置条是**全站挂载**的 —— 它们一旦顺着 plan-kit
// 拖上 content/plans，webpack 就会把 nav 从「所有页面共用的那个 chunk」
// 拆成一个独立 chunk，于是每个路由都要单独再下一遍。
//
// 实测代价（origin/main → 第一版）：课程页 First Load JS 142 → 195 kB（+37%）。
// 把 plan-kit 改成只读这一份之后回到 143 kB。
//
// 所以分工是：
//   构建期 / 服务端   content/plans.ts     完整定义、查询展开、完整性断言
//   全站挂载的客户端  这一份               只有算「我在哪、下一格是什么」要的字段
//   计划详情页        content/plans.ts     它是单独一个路由，重依赖无所谓
//
// 这一份**没有**：每一档的「为什么在这儿」、每一条的估时、覆盖方向。
// 那些只有 /plans/[planId] 用得上，那一页自己去读 content/plans。

import type { PlanItemKind, PlanPhase } from "@/lib/plan-types";

/**
 * 一个条目，按列存 —— 用数组而不是对象是为了不把字段名重复 300 多遍
 * （实测省下 7 KB 原始字节）。列的顺序**只在这里定义一次**：
 *
 *   0  kind     lesson | exercise | drill | coding | arena | mock
 *   1  id       课文 id / 练习 id / 题目 id …
 *   2  examId   lesson、exercise、mock 才有；其余是空串
 *   3  zh       中文标题
 *   4  en       英文标题；没补就是空串（<T> 会回落中文）
 *   5  href     完整路径。**存而不算** —— 路径拼法的唯一真相在 content/nav.ts
 *               的那几个 helper 里，这里再抄一份就会出现两套 URL
 *   6  xkind    只有 exercise 有：练习题型。从零重写那一类的完成记录在
 *               progress.rebuilds 里，其余在 progress.exercises 里
 *   7  minutes  估时（分钟）。0 = 这一类没有估时（练习和八股）
 */
export type ManifestItem = [
  PlanItemKind,
  string,
  string,
  string,
  string,
  string,
  string,
  number,
];

export interface ManifestStage {
  id: string;
  phase: PlanPhase;
  zh: string;
  en: string;
  /** 指向 PLAN_ITEMS 的下标。跨计划共享同一张表，所以「从零完整学习」
   *  和「React 考试准备」里同一节课只存一份 */
  items: number[];
}

export interface ManifestPlan {
  id: string;
  zh: string;
  en: string;
  outcomeZh: string;
  outcomeEn: string;
  forZh: string;
  forEn: string;
  /** 有估时的那些条目的分钟数之和。卡片上那句「约 N 小时」用它 */
  minutes: number;
  stages: ManifestStage[];
}

export const PLAN_ITEMS: ManifestItem[] = [
  ["lesson","node-and-npm","foundations","Node.js、npm、node_modules 和 lockfile","Node.js, npm, node_modules and the lockfile","/exams/foundations/node-and-npm","",12],
  ["lesson","package-json","foundations","package.json 逐字段读一遍","package.json, field by field","/exams/foundations/package-json","",14],
  ["lesson","npm-scripts","foundations","npm scripts：命令到底跑了什么","npm scripts: what the command actually runs","/exams/foundations/npm-scripts","",13],
  ["lesson","project-layout","foundations","两个考试项目的目录，逐个说明","The directory layout of both exam projects","/exams/foundations/project-layout","",12],
  ["lesson","js-immutable-data","foundations","数组与对象：不可变更新三件套","Arrays and objects: three ways to update without changing the original","/exams/foundations/js-immutable-data","",14],
  ["lesson","js-async","foundations","异步：Promise、await、all 和 allSettled","Async: Promise, await, all and allSettled","/exams/foundations/js-async","",15],
  ["lesson","js-modules","foundations","ESM:import / export 与那些莫名其妙的报错","ESM: import / export, and the errors that look strange at first","/exams/foundations/js-modules","",10],
  ["lesson","ts-types","foundations","类型、type 与 interface","Types, type and interface","/exams/foundations/ts-types","",12],
  ["lesson","ts-generics-and-errors","foundations","泛型参数，以及怎么读 tsc 的报错","Generic parameters, and how to read a tsc error","/exams/foundations/ts-generics-and-errors","",12],
  ["exercise","f-dep-place","foundations","这个包该放哪边？","Which side does this package go on?","/exams/foundations/node-and-npm#ex-f-dep-place","recognition",0],
  ["exercise","f-lockfile-rule","foundations","lockfile 该怎么对待","How to treat the lockfile","/exams/foundations/node-and-npm#ex-f-lockfile-rule","recognition",0],
  ["exercise","f-pkg-blanks","foundations","补全 subgraph 的 package.json 关键字段","Fill in the key fields of the subgraph package.json","/exams/foundations/package-json#ex-f-pkg-blanks","fill-blank",0],
  ["exercise","f-how-to-test","foundations","怎么跑 react-notes-app 的测试","How to run the tests of react-notes-app","/exams/foundations/npm-scripts#ex-f-how-to-test","recognition",0],
  ["exercise","f-debug-order","foundations","script 报错了，按什么顺序排查","A script failed: in what order do you check things","/exams/foundations/npm-scripts#ex-f-debug-order","ordering",0],
  ["exercise","f-which-file","foundations","Q1 的 state 应该放在哪个文件","Which file should hold the state for Q1","/exams/foundations/project-layout#ex-f-which-file","recognition",0],
  ["exercise","f-distractor","foundations","哪个是干扰项","Which one is the distractor","/exams/foundations/project-layout#ex-f-distractor","recognition",0],
  ["exercise","f-crud-blanks","foundations","补全 Q1 的三个数据操作","Fill in the three data operations of Q1","/exams/foundations/js-immutable-data#ex-f-crud-blanks","fill-blank",0],
  ["exercise","f-debug-push","foundations","Debug Lab · 数据加进去了，界面没反应","Debug Lab · the data went in, the screen did not move","/exams/foundations/js-immutable-data#ex-f-debug-push","debug",0],
  ["exercise","f-async-all","foundations","该用 all 还是 allSettled","all or allSettled","/exams/foundations/js-async#ex-f-async-all","recognition",0],
  ["exercise","f-async-fn","foundations","为什么 tasks 是「函数数组」而不是「Promise 数组」","Why tasks is an array of functions, not an array of Promises","/exams/foundations/js-async#ex-f-async-fn","recognition",0],
  ["exercise","f-async-blanks","foundations","补全 DataLoader 的批量函数","Fill in the batch function of the DataLoader","/exams/foundations/js-async#ex-f-async-blanks","fill-blank",0],
  ["exercise","f-debug-esm","foundations","Debug Lab · ERR_MODULE_NOT_FOUND","Debug Lab · ERR_MODULE_NOT_FOUND","/exams/foundations/js-modules#ex-f-debug-esm","debug",0],
  ["exercise","f-ts-props","foundations","补全 NoteTable 的 props 类型","Fill in the props type of NoteTable","/exams/foundations/ts-types#ex-f-ts-props","fill-blank",0],
  ["exercise","f-whose-fault","foundations","这是谁的问题","Whose problem is this","/exams/foundations/ts-generics-and-errors#ex-f-whose-fault","recognition",0],
  ["exercise","f-generic-blanks","foundations","补全泛型参数","Fill in the generic parameters","/exams/foundations/ts-generics-and-errors#ex-f-generic-blanks","fill-blank",0],
  ["lesson","r-component","react","组件就是一个返回界面的函数","A component is a function that returns what you see on screen","/exams/react/r-component","",11],
  ["lesson","r-props","react","props：数据往下流，事件往上报","props: data flows down, events go back up","/exams/react/r-props","",12],
  ["lesson","r-state","react","useState：让界面跟着数据变","useState: making the screen follow the data","/exams/react/r-state","",14],
  ["lesson","r-controlled-input","react","受控输入：value + onChange 的闭环","Controlled inputs: the loop between value and onChange","/exams/react/r-controlled-input","",13],
  ["lesson","r-lists-keys","react","列表渲染与 key","Rendering a list, and the key prop","/exams/react/r-lists-keys","",10],
  ["lesson","r-useeffect","react","useEffect：把 props 的变化同步进 state","useEffect: copying a change in props into state","/exams/react/r-useeffect","",15],
  ["lesson","r-derived-lifting","react","派生数据与状态提升：什么不该做成 state","Values you can compute, and lifting state up: what should not be state","/exams/react/r-derived-lifting","",11],
  ["lesson","r-read-q1","react","先读题：三个任务、一条硬约束、四个测试","Read the question first: three tasks, one rule you must not break, four tests","/exams/react/r-read-q1","",13],
  ["lesson","r-task1-add","react","Task 1 · Add：提交表单，新笔记进入表格","Task 1 · Add: submit the form and the new note appears in the table","/exams/react/r-task1-add","",12],
  ["lesson","r-task2-delete","react","Task 2 · Delete：点 Delete，该行按 id 被移除","Task 2 · Delete: click Delete and that one row is removed by id","/exams/react/r-task2-delete","",11],
  ["lesson","r-task3-edit","react","Task 3 · Edit：回填、改文字、就地更新、退出编辑","Task 3 · Edit: refill the form, change the button text, update the row where it is, leave edit mode","/exams/react/r-task3-edit","",18],
  ["lesson","r-tests","react","四个测试逐条读，以及它们的盲区","The four tests read line by line, and what they fail to catch","/exams/react/r-tests","",12],
  ["lesson","r-q2-read","react","读题：三条要求，每一条都在指定一种写法","Reading the question: three requirements, and each one decides how you write it","/exams/react/r-q2-read","",12],
  ["lesson","r-q2-implement","react","实现：worker pool（工人池）","Building it: a worker pool, meaning a fixed number of workers sharing one queue","/exams/react/r-q2-implement","",16],
  ["lesson","r-var-todo","react","变式一 · Todo List","Variation 1 · Todo List","/exams/react/r-var-todo","",14],
  ["lesson","r-var-timer","react","变式二 · 计时器：useEffect 的清理函数","Variation 2 · a timer: the useEffect cleanup function","/exams/react/r-var-timer","",16],
  ["lesson","r-var-fetch","react","变式三 · fetch 取数：loading、error 与竞态","Variation 3 · fetching data: loading, error, and the race between two requests","/exams/react/r-var-fetch","",18],
  ["lesson","r-var-comment-tree","react","变式四 · 递归读取评论的评论","Variation 4 · reading replies to replies with recursion","/exams/react/r-var-comment-tree","",20],
  ["lesson","r-var-theme-context","react","变式五 · 主题切换：Context 怎么用","Variation 5 · theme switching: how to use Context","/exams/react/r-var-theme-context","",20],
  ["lesson","r-debug-lab","react","Debug Lab · React 十种典型故障","Debug Lab · ten typical React failures","/exams/react/r-debug-lab","",20],
  ["lesson","r-rebuild","react","从零重写：空文件夹到 4 个测试全过","Write it again yourself: from an empty folder to 4 passing tests","/exams/react/r-rebuild","",60],
  ["exercise","r-jsx-brace","react","哪一行会把变量的值显示出来","Which line prints the value of a variable","/exams/react/r-component#ex-r-jsx-brace","recognition",0],
  ["exercise","r-where-code","react","三道题的代码该写在哪个文件","Which file the code for the three tasks belongs in","/exams/react/r-component#ex-r-where-code","recognition",0],
  ["exercise","r-props-blanks","react","补全 NoteItem 的两个按钮","Fill in the two buttons of NoteItem","/exams/react/r-props#ex-r-props-blanks","fill-blank",0],
  ["exercise","r-debug-immediate-call","react","Debug Lab · 页面一打开，所有笔记就消失了","Debug Lab · every note disappears the moment the page opens","/exams/react/r-props#ex-r-debug-immediate-call","debug",0],
  ["exercise","r-render-order","react","把一次点击的顺序排对","Put the steps of one click in order","/exams/react/r-state#ex-r-render-order","ordering",0],
  ["exercise","r-write-state","react","自己写出 NoteManager 的两个 state 和删除逻辑","Write the two states of NoteManager and the delete logic yourself","/exams/react/r-state#ex-r-write-state","code-completion",0],
  ["exercise","r-controlled-blanks","react","补全受控输入的闭环","Complete the loop of a controlled input","/exams/react/r-controlled-input#ex-r-controlled-blanks","fill-blank",0],
  ["exercise","r-debug-preventdefault","react","Debug Lab · 点 Add 之后页面闪一下，笔记没了","Debug Lab · the page blinks after Add and the note is gone","/exams/react/r-controlled-input#ex-r-debug-preventdefault","debug",0],
  ["exercise","r-key-choice","react","这个列表该用什么当 key","What should this list use as its key","/exams/react/r-lists-keys#ex-r-key-choice","recognition",0],
  ["exercise","r-map-return","react","哪一段什么都不会渲染","Which one renders nothing at all","/exams/react/r-lists-keys#ex-r-map-return","recognition",0],
  ["exercise","r-effect-blanks","react","补全编辑回填的 useEffect","Complete the useEffect that prefills the form for editing","/exams/react/r-useeffect#ex-r-effect-blanks","fill-blank",0],
  ["exercise","r-debug-effect-loop","react","Debug Lab · 点 Edit 之后页面卡死","Debug Lab · the page freezes after you press Edit","/exams/react/r-useeffect#ex-r-debug-effect-loop","debug",0],
  ["exercise","r-derived-or-state","react","哪个应该做成 state","Which one should become state","/exams/react/r-derived-lifting#ex-r-derived-or-state","recognition",0],
  ["exercise","r-where-state-lives","react","这个 state 该住哪","Where should this state live","/exams/react/r-derived-lifting#ex-r-where-state-lives","recognition",0],
  ["exercise","r-write-derived","react","写出派生数据与按钮文字","Write the computed value and the button text","/exams/react/r-derived-lifting#ex-r-write-derived","code-completion",0],
  ["exercise","r-q1-forbidden","react","哪一处改动会让测试挂掉","Which change makes a test fail","/exams/react/r-read-q1#ex-r-q1-forbidden","recognition",0],
  ["exercise","r-q1-hidden-req","react","题目没写但测试在查的是哪一条","The requirement the task never states but a test checks","/exams/react/r-read-q1#ex-r-q1-hidden-req","recognition",0],
  ["exercise","r-q1-workflow","react","把上手顺序排对","Put the starting steps in order","/exams/react/r-read-q1#ex-r-q1-workflow","ordering",0],
  ["exercise","r-t1-blank","react","补全新增逻辑","Fill in the add logic","/exams/react/r-task1-add#ex-r-t1-blank","fill-blank",0],
  ["exercise","r-t1-write","react","不看答案，自己写出 Task 1","Write Task 1 yourself, without looking at the answer","/exams/react/r-task1-add#ex-r-t1-write","code-completion",0],
  ["exercise","r-t2-blank","react","补全删除逻辑","Fill in the delete logic","/exams/react/r-task2-delete#ex-r-t2-blank","fill-blank",0],
  ["exercise","r-t2-write","react","不看答案，自己写出 Task 2","Write Task 2 yourself, without looking at the answer","/exams/react/r-task2-delete#ex-r-t2-write","code-completion",0],
  ["exercise","r-debug-filter-title","react","Debug Lab · 删一条，同名的全没了","Debug Lab · delete one note and every note with the same title goes too","/exams/react/r-task2-delete#ex-r-debug-filter-title","debug",0],
  ["exercise","r-t3-blank","react","补全编辑逻辑的四个关键位置","Fill in the four key spots of the edit logic","/exams/react/r-task3-edit#ex-r-t3-blank","fill-blank",0],
  ["exercise","r-t3-write","react","不看答案，自己写出完整的 Task 3","Write all of Task 3 yourself, without looking at the answer","/exams/react/r-task3-edit#ex-r-t3-write","code-completion",0],
  ["exercise","r-debug-new-id","react","Debug Lab · 点 Update 之后毫无反应","Debug Lab · nothing happens after you click Update","/exams/react/r-task3-edit#ex-r-debug-new-id","debug",0],
  ["exercise","r-test-blindspot","react","哪个实现能骗过全部四个测试但其实是错的","Which implementation passes all four tests and is still wrong","/exams/react/r-tests#ex-r-test-blindspot","recognition",0],
  ["exercise","r-test-await","react","这个测试失败是因为什么","Why this test fails","/exams/react/r-tests#ex-r-test-await","recognition",0],
  ["exercise","r-write-own-test","react","自己补一个测试，覆盖「按 id 删除」这个盲区","Write a test of your own to cover the delete-by-id blind spot","/exams/react/r-tests#ex-r-write-own-test","code-completion",0],
  ["exercise","r-q2-why-fn","react","如果参数改成 Promise 数组会怎样","What happens if the parameter becomes an array of Promises","/exams/react/r-q2-read#ex-r-q2-why-fn","recognition",0],
  ["exercise","r-q2-not-allsettled","react","为什么不能直接用 Promise.allSettled","Why Promise.allSettled on its own is not the answer","/exams/react/r-q2-read#ex-r-q2-not-allsettled","recognition",0],
  ["exercise","r-q2-blanks","react","补全 worker pool 的五个关键位置","Fill in the five key spots of the worker pool","/exams/react/r-q2-implement#ex-r-q2-blanks","fill-blank",0],
  ["exercise","r-q2-write","react","从签名开始，自己写出整个 runTasks","Start from the signature and write all of runTasks yourself","/exams/react/r-q2-implement#ex-r-q2-write","code-completion",0],
  ["exercise","r-debug-q2-no-parens","react","Debug Lab · 一行 START 都没打印","Debug Lab · not one START line prints","/exams/react/r-q2-implement#ex-r-debug-q2-no-parens","debug",0],
  ["exercise","r-var-todo-blank","react","补全翻转与批量操作","Fill in the toggle and the bulk action","/exams/react/r-var-todo#ex-r-var-todo-blank","fill-blank",0],
  ["exercise","r-var-todo-write","react","自己写出筛选与「清除已完成」","Write the filtering and the clear-completed action yourself","/exams/react/r-var-todo#ex-r-var-todo-write","code-completion",0],
  ["exercise","r-var-timer-blank","react","补全计时器的 effect","Fill in the effect of the timer","/exams/react/r-var-timer#ex-r-var-timer-blank","fill-blank",0],
  ["exercise","r-var-timer-write","react","自己写出整个计时器","Write the whole timer yourself","/exams/react/r-var-timer#ex-r-var-timer-write","code-completion",0],
  ["exercise","r-var-timer-debug","react","Debug Lab · 计时器越跑越快","Debug Lab · the timer keeps getting faster","/exams/react/r-var-timer#ex-r-var-timer-debug","debug",0],
  ["exercise","r-var-fetch-blank","react","补全取数 effect 的四个关键位置","Fill in the four key spots of the fetching effect","/exams/react/r-var-fetch#ex-r-var-fetch-blank","fill-blank",0],
  ["exercise","r-var-fetch-write","react","自己写出带竞态防护的取数 effect","Write the fetching effect with race protection yourself","/exams/react/r-var-fetch#ex-r-var-fetch-write","code-completion",0],
  ["exercise","r-var-fetch-debug","react","Debug Lab · URL 上是用户 2，界面显示用户 1","Debug Lab · the URL says user 2 and the screen shows user 1","/exams/react/r-var-fetch#ex-r-var-fetch-debug","debug",0],
  ["exercise","r-var-tree-blank","react","补全递归统计与递归渲染","Fill in the recursive count and the recursive render","/exams/react/r-var-comment-tree#ex-r-var-tree-blank","fill-blank",0],
  ["exercise","r-var-tree-write","react","写出树形数据的不可变更新","Write an immutable update for tree data","/exams/react/r-var-comment-tree#ex-r-var-tree-write","code-completion",0],
  ["exercise","r-var-tree-debug","react","Debug Lab · 回复加进去了，界面不动","Debug Lab · the reply went in and the screen never moved","/exams/react/r-var-comment-tree#ex-r-var-tree-debug","debug",0],
  ["exercise","r-var-theme-blank","react","补全 ThemeContext 的四个关键位置","Fill in the four key spots of ThemeContext","/exams/react/r-var-theme-context#ex-r-var-theme-blank","fill-blank",0],
  ["exercise","r-var-theme-write","react","自己写出 ThemeProvider 和 useTheme","Write ThemeProvider and useTheme yourself","/exams/react/r-var-theme-context#ex-r-var-theme-write","code-completion",0],
  ["exercise","r-var-theme-debug","react","Debug Lab · Cannot destructure property 'theme'","","/exams/react/r-var-theme-context#ex-r-var-theme-debug","debug",0],
  ["exercise","r-lab-import-path","react","故障 1 · 路径大小写","Fault 1 · upper and lower case in a path","/exams/react/r-debug-lab#ex-r-lab-import-path","debug",0],
  ["exercise","r-lab-props-undefined","react","故障 2 · props 名字对不上","Fault 2 · the prop names do not match","/exams/react/r-debug-lab#ex-r-lab-props-undefined","debug",0],
  ["exercise","r-lab-testid-typo","react","故障 3 · 测试找不到元素","Fault 3 · the test cannot find the element","/exams/react/r-debug-lab#ex-r-lab-testid-typo","debug",0],
  ["exercise","r-lab-silent-mutation","react","故障 4 · 编辑后列表毫无变化（综合题）","Fault 4 · the list does not change after an edit (mixed question)","/exams/react/r-debug-lab#ex-r-lab-silent-mutation","debug",0],
  ["exercise","r-rebuild-q1","react","从零重建 Q1 · Notes Manager","Rebuild Q1 · Notes Manager","/exams/react/r-rebuild#ex-r-rebuild-q1","from-scratch",0],
  ["exercise","r-rebuild-q2","react","从零重建 Q2 · 并发任务调度器","Rebuild Q2 · the concurrent task runner","/exams/react/r-rebuild#ex-r-rebuild-q2","from-scratch",0],
  ["coding","todo-list","","Todo List","","/code/todo-list","",25],
  ["coding","timer","","计时器（useEffect 清理函数）","Timer (useEffect cleanup)","/code/timer","",25],
  ["coding","fetch-user","","fetch 取数：loading、error 与竞态","Fetching data: loading, error and race conditions","/code/fetch-user","",35],
  ["coding","comment-tree","","递归评论树 + 树形不可变更新","Recursive comment tree, updated without changing the original","/code/comment-tree","",35],
  ["coding","theme-context","","主题切换（Context + value 记忆化）","Theme switch (Context plus a memoised value)","/code/theme-context","",30],
  ["coding","notes-manager","","Notes Manager 增删改（React 考试 Q1）","Notes Manager: add, edit and delete (React exam Q1)","/code/notes-manager","",60],
  ["coding","run-tasks","","带并发上限的异步任务调度器（Q2）","Async task scheduler with a concurrency limit (Q2)","/code/run-tasks","",45],
  ["arena","r-rebuild-q1","","从零重建 Q1 · Notes Manager","Rebuild Q1 · Notes Manager","/arena/r-rebuild-q1","",75],
  ["arena","r-rebuild-q2","","从零重建 Q2 · 并发任务调度器","Rebuild Q2 · the concurrent task runner","/arena/r-rebuild-q2","",45],
  ["mock","support-tickets","react","模拟考 A · Support Ticket Board","Mock exam A · Support Ticket Board","/mock/react/support-tickets","",75],
  ["lesson","g-what-is","graphql-federation","GraphQL 是什么：一份 schema 加一堆 resolver","What GraphQL is: one schema plus a set of resolvers","/exams/graphql-federation/g-what-is","",15],
  ["lesson","g-resolver","graphql-federation","resolver 的四个参数","The four arguments of a resolver","/exams/graphql-federation/g-resolver","",14],
  ["lesson","g-nullable","graphql-federation","非空、列表，和那个没有 price 的 input","Non-null, lists, and the input that has no price","/exams/graphql-federation/g-nullable","",13],
  ["lesson","g-why-federation","graphql-federation","为什么会有 Federation","Why Federation exists","/exams/graphql-federation/g-why-federation","",11],
  ["lesson","g-subgraph","graphql-federation","subgraph 是怎么跑起来的","How a subgraph starts up","/exams/graphql-federation/g-subgraph","",13],
  ["lesson","g-entity","graphql-federation","entity、@key 与 __resolveReference","entity, @key and __resolveReference","/exams/graphql-federation/g-entity","",16],
  ["lesson","g-dataloader","graphql-federation","N+1 问题与 DataLoader","The N+1 problem and DataLoader","/exams/graphql-federation/g-dataloader","",14],
  ["lesson","g-read-task1","graphql-federation","先读题：四个 TODO、三处埋雷、十个测试","Read the task first: four TODOs, three planted bugs, ten tests","/exams/graphql-federation/g-read-task1","",15],
  ["lesson","g-user-orders","graphql-federation","TODO 1 · User.orders","TODO 1 · User.orders","/exams/graphql-federation/g-user-orders","",13],
  ["lesson","g-shipping-info","graphql-federation","TODO 2 · Order.shippingInfo","TODO 2 · Order.shippingInfo","/exams/graphql-federation/g-shipping-info","",11],
  ["lesson","g-queries","graphql-federation","TODO 3 & 4 · Query.order 与 Query.orders","TODO 3 & 4 · Query.order and Query.orders","/exams/graphql-federation/g-queries","",14],
  ["lesson","g-planted-bugs","graphql-federation","三处埋雷：怎么系统地找出来","The three planted bugs: how to find them systematically","/exams/graphql-federation/g-planted-bugs","",16],
  ["lesson","g-spring-basics","graphql-federation","先看懂给你的东西：Spring 的几个注解和一条请求链路","Understand what you are given: a few Spring annotations and the path one request takes","/exams/graphql-federation/g-spring-basics","",16],
  ["lesson","g-endpoints","graphql-federation","六个端点：状态码就是这道题的全部","Six endpoints: the status codes are the whole task","/exams/graphql-federation/g-endpoints","",18],
  ["lesson","g-written","graphql-federation","两道书面题：延迟传播与生产配置","The two written questions: how delay spreads, and production configuration","/exams/graphql-federation/g-written","",22],
  ["lesson","g-debug-lab","graphql-federation","Debug Lab · Federation 十种典型故障","Debug Lab · ten common Federation failures","/exams/graphql-federation/g-debug-lab","",22],
  ["lesson","g-rebuild","graphql-federation","从零重写：空目录到 10 个测试全过","Rewrite it: from an empty directory to all 10 tests passing","/exams/graphql-federation/g-rebuild","",90],
  ["exercise","g-which-is-scalar","graphql-federation","哪些字段是标量","Which fields are scalars","/exams/graphql-federation/g-what-is#ex-g-which-is-scalar","recognition",0],
  ["exercise","g-query-vs-mutation","graphql-federation","这个操作该放哪","Where does this operation belong","/exams/graphql-federation/g-what-is#ex-g-query-vs-mutation","recognition",0],
  ["exercise","g-schema-blanks","graphql-federation","补全 schema 的关键声明","Fill in the key declarations of the schema","/exams/graphql-federation/g-what-is#ex-g-schema-blanks","fill-blank",0],
  ["exercise","g-context-key","graphql-federation","从 context 里取订单数据源，正确写法是","The right way to read the order data source out of context","/exams/graphql-federation/g-resolver#ex-g-context-key","recognition",0],
  ["exercise","g-which-param","graphql-federation","这个 resolver 该用哪个参数","Which argument should this resolver use","/exams/graphql-federation/g-resolver#ex-g-which-param","recognition",0],
  ["exercise","g-resolver-order","graphql-federation","把 resolver 的调用顺序排对","Put the resolver calls in the right order","/exams/graphql-federation/g-resolver#ex-g-resolver-order","ordering",0],
  ["exercise","g-nullable-return","graphql-federation","这个 resolver 找不到数据时该返回什么","What should this resolver return when it finds nothing","/exams/graphql-federation/g-nullable#ex-g-nullable-return","recognition",0],
  ["exercise","g-price-trap","graphql-federation","createOrder 为什么必须查价格","Why createOrder has to look up the price","/exams/graphql-federation/g-nullable#ex-g-price-trap","recognition",0],
  ["exercise","g-nullable-blanks","graphql-federation","给四个 TODO 各自选对兜底策略","Pick the right fallback for each of the four TODOs","/exams/graphql-federation/g-nullable#ex-g-nullable-blanks","fill-blank",0],
  ["exercise","g-fed-why","graphql-federation","Federation 主要解决的是什么问题","What problem does Federation mainly solve","/exams/graphql-federation/g-why-federation#ex-g-fed-why","recognition",0],
  ["exercise","g-not-in-repo","graphql-federation","哪些东西不在这个仓库里","What is not in this repository","/exams/graphql-federation/g-why-federation#ex-g-not-in-repo","recognition",0],
  ["exercise","g-build-subgraph","graphql-federation","_entities 这个字段是谁加的","Who adds the _entities field","/exams/graphql-federation/g-subgraph#ex-g-build-subgraph","recognition",0],
  ["exercise","g-verify-how","graphql-federation","本地怎么验证 federation 部分","How to check the Federation part locally","/exams/graphql-federation/g-subgraph#ex-g-verify-how","recognition",0],
  ["exercise","g-key-meaning","graphql-federation","@key 在声明什么","What @key declares","/exams/graphql-federation/g-entity#ex-g-key-meaning","recognition",0],
  ["exercise","g-parent-of-orders","graphql-federation","User.orders 里的 user 参数上有什么","What the user argument of User.orders carries","/exams/graphql-federation/g-entity#ex-g-parent-of-orders","recognition",0],
  ["exercise","g-entity-blanks","graphql-federation","补全 entity 声明与引用解析","Fill in the entity declaration and the reference resolver","/exams/graphql-federation/g-entity#ex-g-entity-blanks","fill-blank",0],
  ["exercise","g-dataloader-why","graphql-federation","DataLoader 靠什么把 N 次合并成 1 次","How DataLoader turns N calls into 1","/exams/graphql-federation/g-dataloader#ex-g-dataloader-why","recognition",0],
  ["exercise","g-batch-rules","graphql-federation","batch 函数里哪种写法是错的","Which return value from a batch function is wrong","/exams/graphql-federation/g-dataloader#ex-g-batch-rules","recognition",0],
  ["exercise","g-loader-blanks","graphql-federation","修好 createOrderLoader 并写出 shippingInfo","Fix createOrderLoader and write shippingInfo","/exams/graphql-federation/g-dataloader#ex-g-loader-blanks","fill-blank",0],
  ["exercise","g-debug-loader-method","graphql-federation","Debug Lab · DataLoader 报 is not a function","Debug Lab · DataLoader reports is not a function","/exams/graphql-federation/g-dataloader#ex-g-debug-loader-method","debug",0],
  ["exercise","g-fake-pass","graphql-federation","为什么基线里有 4 个测试是通过的","Why 4 tests already pass at the baseline","/exams/graphql-federation/g-read-task1#ex-g-fake-pass","recognition",0],
  ["exercise","g-fix-where","graphql-federation","埋雷 1 该在哪个文件修","Which file should planted bug 1 be fixed in","/exams/graphql-federation/g-read-task1#ex-g-fix-where","recognition",0],
  ["exercise","g-task1-order","graphql-federation","把 Task 1 的推进顺序排对","Put the steps of Task 1 in the right order","/exams/graphql-federation/g-read-task1#ex-g-task1-order","ordering",0],
  ["exercise","g-t1-blank","graphql-federation","补全 User.orders","Fill in User.orders","/exams/graphql-federation/g-user-orders#ex-g-t1-blank","fill-blank",0],
  ["exercise","g-t1-write","graphql-federation","不看答案，自己写出 User.orders","Write User.orders yourself, without looking at the answer","/exams/graphql-federation/g-user-orders#ex-g-t1-write","code-completion",0],
  ["exercise","g-t2-blank","graphql-federation","补全 Order.shippingInfo","Fill in Order.shippingInfo","/exams/graphql-federation/g-shipping-info#ex-g-t2-blank","fill-blank",0],
  ["exercise","g-t2-why-loader","graphql-federation","为什么不能直接调数据源","Why you cannot just call the data source","/exams/graphql-federation/g-shipping-info#ex-g-t2-why-loader","recognition",0],
  ["exercise","g-t34-blank","graphql-federation","补全两个 Query resolver","Fill in both Query resolvers","/exams/graphql-federation/g-queries#ex-g-t34-blank","fill-blank",0],
  ["exercise","g-t34-write","graphql-federation","不看答案，自己写出两个 Query resolver","Write both Query resolvers yourself, without looking at the answer","/exams/graphql-federation/g-queries#ex-g-t34-write","code-completion",0],
  ["exercise","g-debug-orderapi","graphql-federation","Debug Lab · Cannot read properties of undefined","Debug Lab · Cannot read properties of undefined","/exams/graphql-federation/g-planted-bugs#ex-g-debug-orderapi","debug",0],
  ["exercise","g-debug-swallowed","graphql-federation","Debug Lab · 错误码不对（不报错的那种 bug）","Debug Lab · The wrong error code (the kind of bug that throws nothing)","/exams/graphql-federation/g-planted-bugs#ex-g-debug-swallowed","debug",0],
  ["exercise","g-spring-exception","graphql-federation","找不到订单时该怎么处理","What to do when the order is not found","/exams/graphql-federation/g-spring-basics#ex-g-spring-exception","recognition",0],
  ["exercise","g-spring-annotations","graphql-federation","这三个参数注解各从哪取值","Where each of these parameter annotations reads from","/exams/graphql-federation/g-spring-basics#ex-g-spring-annotations","recognition",0],
  ["exercise","g-status-post","graphql-federation","POST 创建成功该返回什么","What a successful POST should return","/exams/graphql-federation/g-endpoints#ex-g-status-post","recognition",0],
  ["exercise","g-null-passes","graphql-federation","为什么 return null 能骗过三个测试","Why return null fools three of the tests","/exams/graphql-federation/g-endpoints#ex-g-null-passes","recognition",0],
  ["exercise","g-endpoints-blank","graphql-federation","补全三个关键端点的状态码与调用","Fill in the status codes and calls of three key endpoints","/exams/graphql-federation/g-endpoints#ex-g-endpoints-blank","fill-blank",0],
  ["exercise","g-endpoints-write","graphql-federation","不看答案，自己写出全部六个端点","Write all six endpoints yourself, without looking at the answer","/exams/graphql-federation/g-endpoints#ex-g-endpoints-write","code-completion",0],
  ["exercise","g-debug-404-swallowed","graphql-federation","Debug Lab · 查一个不存在的订单，返回了 200","Debug Lab · Asking for an order that does not exist returns 200","/exams/graphql-federation/g-endpoints#ex-g-debug-404-swallowed","debug",0],
  ["exercise","g-written-worst","graphql-federation","哪一行是最严重的安全问题","Which line is the most serious security problem","/exams/graphql-federation/g-written#ex-g-written-worst","recognition",0],
  ["exercise","g-written-serial","graphql-federation","为什么 User subgraph 慢会拖慢 Orders subgraph","Why a slow User subgraph slows the Orders subgraph down","/exams/graphql-federation/g-written#ex-g-written-serial","recognition",0],
  ["exercise","g-written-fix","graphql-federation","写出 actuator 那一条的修正配置","Write the corrected configuration for the actuator line","/exams/graphql-federation/g-written#ex-g-written-fix","code-completion",0],
  ["exercise","g-lab-resolver-name","graphql-federation","故障 1 · resolver 写了，字段还是 null","Fault 1 · the resolver is written, the field is still null","/exams/graphql-federation/g-debug-lab#ex-g-lab-resolver-name","debug",0],
  ["exercise","g-lab-nonnull","graphql-federation","故障 2 · Cannot return null for non-nullable field","Fault 2 · Cannot return null for non-nullable field","/exams/graphql-federation/g-debug-lab#ex-g-lab-nonnull","debug",0],
  ["exercise","g-lab-loader-order","graphql-federation","故障 3 · A 拿到了 B 的数据","Fault 3 · A receives B's data","/exams/graphql-federation/g-debug-lab#ex-g-lab-loader-order","debug",0],
  ["exercise","g-lab-java-500","graphql-federation","故障 4 · PATCH 传了小写状态，返回 500","Fault 4 · PATCH sends a lowercase status and gets a 500","/exams/graphql-federation/g-debug-lab#ex-g-lab-java-500","debug",0],
  ["exercise","g-rebuild-subgraph","graphql-federation","从零重建 Task 1 · Orders subgraph","Rebuild Task 1 · the Orders subgraph","/exams/graphql-federation/g-rebuild#ex-g-rebuild-subgraph","from-scratch",0],
  ["exercise","g-rebuild-controller","graphql-federation","从零重建 Task 2 · Spring Boot 控制器","Rebuild Task 2 · the Spring Boot controller","/exams/graphql-federation/g-rebuild#ex-g-rebuild-controller","from-scratch",0],
  ["coding","orders-subgraph","","Orders subgraph：四个 resolver + DataLoader","Orders subgraph: four resolvers and DataLoader","/code/orders-subgraph","",90],
  ["coding","spring-endpoints","","六个 Spring Boot REST 端点","Six Spring Boot REST endpoints","/code/spring-endpoints","",75],
  ["arena","g-rebuild-subgraph","","从零重建 Task 1 · Orders subgraph","Rebuild Task 1 · the Orders subgraph","/arena/g-rebuild-subgraph","",90],
  ["arena","g-rebuild-controller","","从零重建 Task 2 · Spring Boot 控制器","Rebuild Task 2 · the Spring Boot controller","/arena/g-rebuild-controller","",75],
  ["mock","book-reviews","graphql-federation","模拟考 B · Book Reviews Subgraph","Mock exam B · Book Reviews Subgraph","/mock/graphql-federation/book-reviews","",90],
  ["lesson","cb-read-tests","cab-booking","先读四个测试：它们到底要什么","Read the four tests first: what exactly they ask for","/exams/cab-booking/cb-read-tests","",14],
  ["lesson","cb-provider-layer","cab-booking","Context 放在哪一层 —— 这道题最容易死的地方","Which level the Context goes on — the most common way to fail this task","/exams/cab-booking/cb-provider-layer","",16],
  ["lesson","cb-page-machine","cab-booking","用一个 state 管四个页面","Controlling four pages with one piece of state","/exams/cab-booking/cb-page-machine","",15],
  ["lesson","cb-options-grid","cab-booking","按类型分组渲染六张卡","Rendering the six cards grouped by type","/exams/cab-booking/cb-options-grid","",13],
  ["lesson","cb-loading-timer","cab-booking","Loading：一秒之后自己跳走","Loading: it moves to the next page by itself after one second","/exams/cab-booking/cb-loading-timer","",14],
  ["lesson","cb-history-three","cab-booking","历史与确认页：两个小而致命的细节","The history and confirmation pages: two small details that decide pass or fail","/exams/cab-booking/cb-history-three","",15],
  ["lesson","cb-scaffold-bug","cab-booking","完整答案跑不起来 —— 一个扩展名的事","The complete answer does not run — the cause is one file extension","/exams/cab-booking/cb-scaffold-bug","",13],
  ["lesson","cb-rewrite","cab-booking","从零重写：空文件夹里做出来","Rewrite it: build the whole app in an empty folder","/exams/cab-booking/cb-rewrite","",55],
  ["exercise","cb-tests-recognition","cab-booking","哪个断言决定了「分组顺序」不能自己定？","Which assertion makes the group order fixed?","/exams/cab-booking/cb-read-tests#ex-cb-tests-recognition","recognition",0],
  ["exercise","cb-testid-fill","cab-booking","补齐 RideHistory 的两个 testid 和互斥逻辑","Fill in the two testids of RideHistory and the either-or logic","/exams/cab-booking/cb-read-tests#ex-cb-testid-fill","fill-blank",0],
  ["exercise","cb-context-fill","cab-booking","补齐 Context 三件套","Fill in the three parts of the Context","/exams/cab-booking/cb-provider-layer#ex-cb-context-fill","fill-blank",0],
  ["exercise","cb-context-write","cab-booking","从签名写出整个 CabContext","Write the whole CabContext from the signature","/exams/cab-booking/cb-provider-layer#ex-cb-context-write","code-completion",0],
  ["exercise","cb-flow-order","cab-booking","把一次完整预订的六步排好","Put the six steps of one full booking in order","/exams/cab-booking/cb-page-machine#ex-cb-flow-order","ordering",0],
  ["exercise","cb-app-fill","cab-booking","补齐 App 的状态机","Fill in the state machine of App","/exams/cab-booking/cb-page-machine#ex-cb-app-fill","fill-blank",0],
  ["exercise","cb-keys-recognition","cab-booking","哪个 key 在历史列表里会出问题？","Which key goes wrong in the history list?","/exams/cab-booking/cb-options-grid#ex-cb-keys-recognition","recognition",0],
  ["exercise","cb-card-write","cab-booking","从零写出 CabCard","Write CabCard from an empty file","/exams/cab-booking/cb-options-grid#ex-cb-card-write","code-completion",0],
  ["exercise","cb-loading-fill","cab-booking","补齐 Loading 的四个空","Fill in the four blanks of Loading","/exams/cab-booking/cb-loading-timer#ex-cb-loading-fill","fill-blank",0],
  ["exercise","cb-timer-debug","cab-booking","Debug Lab：定时器永远不到期","Debug Lab: the timer never fires","/exams/cab-booking/cb-loading-timer#ex-cb-timer-debug","debug",0],
  ["exercise","cb-slice-recognition","cab-booking","哪些写法能让测试 4 全绿？（多选）","Which versions make test 4 pass? (more than one)","/exams/cab-booking/cb-history-three#ex-cb-slice-recognition","recognition",0],
  ["exercise","cb-history-write","cab-booking","从零写出 RideHistory","Write RideHistory from an empty file","/exams/cab-booking/cb-history-three#ex-cb-history-write","code-completion",0],
  ["exercise","cb-ext-debug","cab-booking","Debug Lab：0 个测试跑起来","Debug Lab: zero tests run","/exams/cab-booking/cb-scaffold-bug#ex-cb-ext-debug","debug",0],
  ["exercise","cb-better-recognition","cab-booking","下面哪些说法是对的？（多选）","Which of these statements are correct? (more than one)","/exams/cab-booking/cb-scaffold-bug#ex-cb-better-recognition","recognition",0],
  ["exercise","cb-from-scratch","cab-booking","空文件夹里做出整个 Cab Booking","Build the whole of Cab Booking from an empty folder","/exams/cab-booking/cb-rewrite#ex-cb-from-scratch","from-scratch",0],
  ["coding","cab-booking-app","","Cab Booking（Context 版）","Cab Booking (Context version)","/code/cab-booking-app","",45],
  ["arena","cb-from-scratch","","空文件夹里做出整个 Cab Booking","Build the whole of Cab Booking from an empty folder","/arena/cb-from-scratch","",60],
  ["drill","q269","","块级元素 vs 行内元素","Block element vs Inline element","/drill/q269","",0],
  ["drill","q380","","事件冒泡 vs 事件捕获","Event bubbling vs Event capturing","/drill/q380","",0],
  ["drill","q381","","meta 标签有什么用","What is the importance of the meta tag?","/drill/q381","",0],
  ["drill","q382","","什么是语义化标签","What are Semantic Elements?","/drill/q382","",0],
  ["drill","q385","","无障碍、可用性、包容性","Could you explain accessibility, usability, and inclusion? Give some examples of each one in terms of web design.","/drill/q385","",0],
  ["drill","q271","","什么是盒模型","What is the Box Model","/drill/q271","",0],
  ["drill","q272","","margin vs padding","Margin vs Padding","/drill/q272","",0],
  ["drill","q273","","Flexbox vs Grid","Flexbox vs Grid","/drill/q273","",0],
  ["drill","q383","","CSS 选择器有哪些类型","What are the different types of CSS selectors?","/drill/q383","",0],
  ["drill","q270","","有几种方式引入 CSS","How many ways to import CSS in your project","/drill/q270","",0],
  ["drill","q275","","什么是 SCSS","What is SCSS","/drill/q275","",0],
  ["drill","q384","","CSS 预处理器的优缺点","What is a CSS preprocessor? What are the advantages and disadvantages, if any, to using them over plain CSS?","/drill/q384","",0],
  ["drill","q274","","什么是响应式设计，怎么做","What is responsive web design and how to achieve this","/drill/q274","",0],
  ["drill","q276","","什么是 JavaScript 引擎","What is the JavaScript engine","/drill/q276","",0],
  ["drill","q277","","什么是 REPL","What is REPL","/drill/q277","",0],
  ["drill","q278","","原始值 vs 引用值","Primitive data types vs Reference data types","/drill/q278","",0],
  ["drill","q279","","隐式转换 vs 显式转换","Type coercion vs Type conversion","/drill/q279","",0],
  ["drill","q280","","== 和 === 的区别","What is the difference between == and ===","/drill/q280","",0],
  ["drill","q281","","什么是短路求值","What is short-circuit evaluation","/drill/q281","",0],
  ["drill","q282","","var、let、const 的区别","What is the difference between var, let and const","/drill/q282","",0],
  ["drill","q284","","传值 vs 传引用","Pass by Value vs Pass by Reference","/drill/q284","",0],
  ["drill","q286","","Set vs Array","Set vs Array","/drill/q286","",0],
  ["drill","q287","","Map vs Object","Map vs Object","/drill/q287","",0],
  ["drill","q285","","有几种定义函数的方式","How many ways to define a function","/drill/q285","",0],
  ["drill","q290","","什么是一等函数","What is a first class function","/drill/q290","",0],
  ["drill","q291","","什么是一阶函数","What is a first order function","/drill/q291","",0],
  ["drill","q292","","什么是高阶函数","What is a higher order function","/drill/q292","",0],
  ["drill","q293","","什么是纯函数","What is a pure function","/drill/q293","",0],
  ["drill","q294","","\"use strict\" 是干什么的","What is \"use strict\"","/drill/q294","",0],
  ["drill","q295","","作用域有哪几种","What are the different type of scopes","/drill/q295","",0],
  ["drill","q296","","什么是变量提升","What is hoisting","/drill/q296","",0],
  ["drill","q297","","什么是作用域链","What is the scope chain?","/drill/q297","",0],
  ["drill","q298","","什么是闭包","What is a closure","/drill/q298","",0],
  ["drill","q299","","什么是柯里化","What is currying","/drill/q299","",0],
  ["drill","q300","","什么是 IIFE","What is an IIFE","/drill/q300","",0],
  ["drill","q302","","什么是面向对象编程","What is Object-Oriented Programming (OOP)","/drill/q302","",0],
  ["drill","q303","","this 指向什么","What does 'this' refer to","/drill/q303","",0],
  ["drill","q304","","call、apply、bind 的区别","What are the differences between call, apply & bind","/drill/q304","",0],
  ["drill","q305","","事件循环是怎么工作的","What does the event loop","/drill/q305","",0],
  ["drill","q306","","async/await vs Promise","Async/await vs Promise","/drill/q306","",0],
  ["drill","q307","","什么是回调地狱","What is callback hell","/drill/q307","",0],
  ["drill","q309","","Promise 链里的 finally() 有什么用","What is the purpose of the finally() method in a Promise chain","/drill/q309","",0],
  ["drill","q310","","错误处理怎么做","Error Handling","/drill/q310","",0],
  ["drill","q311","","怎么处理异步操作","Handle asynchronous operations","/drill/q311","",0],
  ["drill","q288","","什么是 DOM，什么是 DOM 事件","What is the DOM and what is DOM event","/drill/q288","",0],
  ["drill","q289","","事件传播 vs 事件委托","Event propagation vs Event delegation","/drill/q289","",0],
  ["drill","q301","","ES6 有哪些新特性","Name the new ES6 features","/drill/q301","",0],
  ["drill","q308","","什么是 ES6 模块","What are ES6 modules","/drill/q308","",0],
  ["drill","q312","","什么是 npm","What is npm","/drill/q312","",0],
  ["drill","q283","","Webpack 是怎么工作的","How does Webpack work","/drill/q283","",0],
  ["drill","q387","","fetch 和 axios 的区别","What is the difference between making server requests via fetch and axios?","/drill/q387","",0],
  ["drill","q321","","什么是 SPA","What is a SPA","/drill/q321","",0],
  ["drill","q320","","React 的优势是什么","React advantage","/drill/q320","",0],
  ["drill","q319","","React vs Angular","React vs Angular","/drill/q319","",0],
  ["drill","q326","","什么是 JSX","What is JSX","/drill/q326","",0],
  ["drill","q330","","虚拟 DOM 和 diff 算法","Virtual DOM and diffing algorithm","/drill/q330","",0],
  ["drill","q353","","什么是 reconciliation","What is reconciliation","/drill/q353","",0],
  ["drill","q337","","React 项目里 babel 和 webpack 干什么","What do we use babel and web pack for in React applications","/drill/q337","",0],
  ["drill","q322","","函数组件 vs 类组件","Functional components vs Class components","/drill/q322","",0],
  ["drill","q323","","React 的生命周期有哪些","Explain the React component lifecycle and its methods","/drill/q323","",0],
  ["drill","q325","","useEffect 和生命周期怎么对应","UseEffect vs Lifecycle Methods","/drill/q325","",0],
  ["drill","q327","","props vs state","props vs state","/drill/q327","",0],
  ["drill","q328","","组件之间怎么通信","Communication between components","/drill/q328","",0],
  ["drill","q329","","受控组件 vs 非受控组件","Controlled component vs uncontrolled component","/drill/q329","",0],
  ["drill","q345","","什么是状态提升","What is Lifting State Up in React","/drill/q345","",0],
  ["drill","q331","","什么是 props drilling","What is props drilling","/drill/q331","",0],
  ["drill","q336","","什么是 Pure Component","What are Pure Component","/drill/q336","",0],
  ["drill","q338","","什么是 Fragment","React Fragment","/drill/q338","",0],
  ["drill","q335","","什么是 HOC","What is HOC","/drill/q335","",0],
  ["drill","q324","","什么是 hooks，为什么要用","What are hooks in React and Why do we use them","/drill/q324","",0],
  ["drill","q339","","useMemo vs useCallback","useMemo vs useCallback","/drill/q339","",0],
  ["drill","q346","","React.memo vs useMemo","React.memo vs useMemo","/drill/q346","",0],
  ["drill","q340","","自定义 hook 是干什么的，命名有什么约定","What are custom hooks for and what is the naming convention for them","/drill/q340","",0],
  ["drill","q343","","怎么优化 React 性能","How could you improve performance in React","/drill/q343","",0],
  ["drill","q342","","React 里怎么写样式","How to use styles in React","/drill/q342","",0],
  ["drill","q344","","React 18 有哪些新变化","What are the new changes in react 18","/drill/q344","",0],
  ["drill","q347","","React.lazy 是干什么的","What is React lazy function","/drill/q347","",0],
  ["drill","q332","","什么是 StrictMode","What is React strict mode","/drill/q332","",0],
  ["drill","q333","","什么是错误边界，有什么用","What are error boundaries and How are they useful","/drill/q333","",0],
  ["drill","q334","","React Router 的意义是什么","React router, What is the point of it","/drill/q334","",0],
  ["drill","q348","","写 React 时你会注意哪些最佳实践","When coding React, what are some best practices that you keep in mind","/drill/q348","",0],
  ["drill","q349","","Redux vs Context API","Redux vs Context API","/drill/q349","",0],
  ["drill","q350","","Redux 的结构和工作流","Redux structure and workflow","/drill/q350","",0],
  ["drill","q352","","Redux 的三大原则","Redux 3 main principles","/drill/q352","",0],
  ["drill","q354","","解释一下 Redux 中间件","explain Redux Middleware","/drill/q354","",0],
  ["drill","q355","","JavaScript vs TypeScript","Javascript vs TypeScript","/drill/q355","",0],
  ["drill","q356","","什么是静态类型检查，有什么好处","What is static type checking and how can developers benefit from it","/drill/q356","",0],
  ["drill","q313","","Node.js 的事件循环是怎么工作的","How does the event loop work in Node.js","/drill/q313","",0],
  ["drill","q314","","请求 - 响应周期是怎样的","Explain the request & response cycle","/drill/q314","",0],
  ["drill","q315","","查询参数 vs 路径参数","Query parameters vs Path parameters","/drill/q315","",0],
  ["drill","q316","","什么是 CRUD","What is CRUD","/drill/q316","",0],
  ["drill","q317","","关系型数据库 vs 非关系型数据库","Relational database vs Non-relational database","/drill/q317","",0],
  ["drill","q318","","主键 vs 外键","Primary key vs Foreign key","/drill/q318","",0],
  ["drill","q360","","什么是 CORS，怎么解决 CORS 错误","What is CORS and how to solve the CORS error","/drill/q360","",0],
  ["drill","q358","","HTTPS vs HTTP","HTTPS vs HTTP","/drill/q358","",0],
  ["drill","q359","","什么是 JWT","What is JWT","/drill/q359","",0],
  ["drill","q361","","session vs cookie","sessions vs cookies","/drill/q361","",0],
  ["drill","q362","","常见的 HTTP 状态码","Give some HTTP response status codes","/drill/q362","",0],
  ["drill","q357","","测试有哪几种","What are the different kinds of tests","/drill/q357","",0],
  ["drill","ts1","","Partial、Required、Pick、Omit、Record 分别解决什么问题","What problems do Partial, Required, Pick, Omit and Record each solve","/drill/ts1","",0],
  ["drill","ts2","","手写 MyPick 和 MyPartial","Implement Pick and Partial by hand","/drill/ts2","",0],
  ["drill","ts3","","Exclude、Extract、ReturnType 是怎么实现的","How are Exclude, Extract and ReturnType implemented","/drill/ts3","",0],
  ["drill","ts4","","为什么 getProp 必须写 K extends keyof T","Why does getProp need the constraint K extends keyof T","/drill/ts4","",0],
  ["drill","ts5","","判别联合怎么配合 switch 做穷尽检查","How do discriminated unions enable exhaustiveness checking","/drill/ts5","",0],
  ["drill","ts6","","unknown、any、never 各自是什么语义","What do unknown, any and never each mean","/drill/ts6","",0],
  ["lesson","iv-coding-map","interview","16 道题逐题对照","The 16 problems, compared one by one","/exams/interview/iv-coding-map","",12],
  ["lesson","iv-coding-widgets","interview","缺口一 · Dropdown、Tabs、星级评分","Gap 1 · dropdown, tabs and star rating","/exams/interview/iv-coding-widgets","",24],
  ["lesson","iv-coding-ref-hook","interview","缺口二 · useRef 操作 DOM，与写一个自定义 hook","Gap 2 · using useRef on the DOM, and writing a custom hook","/exams/interview/iv-coding-ref-hook","",22],
  ["lesson","iv-coding-rtk","interview","缺口三 · 同一个 Todo 换成 Redux Toolkit","Gap 3 · the same Todo app, moved to Redux Toolkit","/exams/interview/iv-coding-rtk","",24],
  ["lesson","iv-coding-kanban","interview","缺口四 · Kanban 看板：一次改两个数组","Gap 4 · a Kanban board: changing two arrays in one update","/exams/interview/iv-coding-kanban","",20],
  ["lesson","iv-hand-timing","interview","计时两兄弟：debounce 与 throttle","Two timing helpers: debounce and throttle","/exams/interview/iv-hand-timing","",30],
  ["lesson","iv-hand-data","interview","数据与函数：deepClone、flatten、curry","Data and functions: deepClone, flatten, curry","/exams/interview/iv-hand-data","",35],
  ["lesson","iv-hand-async","interview","异步与结构：Promise.all、EventEmitter、LRU","Async and structure: Promise.all, EventEmitter, LRU","/exams/interview/iv-hand-async","",35],
  ["lesson","iv-ts-utility","interview","Utility Types：会用，还要会手写","Utility types: use them, and write them yourself","/exams/interview/iv-ts-utility","",28],
  ["lesson","iv-ts-generics","interview","泛型与收窄：把 any 赶出代码","Generics and narrowing: getting any out of the code","/exams/interview/iv-ts-generics","",26],
  ["exercise","iv-coding-recog","interview","认出考点：这道题在考什么","Name the point: what is this question testing","/exams/interview/iv-coding-map#ex-iv-coding-recog","recognition",0],
  ["exercise","iv-coding-dropdown-blank","interview","补全「点外面关掉」","Fill in \"click outside closes it\"","/exams/interview/iv-coding-widgets#ex-iv-coding-dropdown-blank","fill-blank",0],
  ["exercise","iv-coding-stars-write","interview","自己写出星级评分","Write the star rating yourself","/exams/interview/iv-coding-widgets#ex-iv-coding-stars-write","code-completion",0],
  ["exercise","iv-coding-hook-write","interview","自己写出 useLocalStorage","Write useLocalStorage yourself","/exams/interview/iv-coding-ref-hook#ex-iv-coding-hook-write","code-completion",0],
  ["exercise","iv-coding-rtk-blank","interview","补全 createSlice","Fill in createSlice","/exams/interview/iv-coding-rtk#ex-iv-coding-rtk-blank","fill-blank",0],
  ["exercise","iv-coding-kanban-write","interview","写出 moveCard","Write moveCard","/exams/interview/iv-coding-kanban#ex-iv-coding-kanban-write","code-completion",0],
  ["exercise","hd-debounce-write","interview","手写 debounce（带 cancel）","Write debounce by hand (with cancel)","/exams/interview/iv-hand-timing#ex-hd-debounce-write","code-completion",0],
  ["exercise","hd-throttle-write","interview","手写 throttle（leading + trailing）","Write throttle by hand (leading + trailing)","/exams/interview/iv-hand-timing#ex-hd-throttle-write","code-completion",0],
  ["exercise","hd-clone-write","interview","手写 deepClone（防循环）","Write deepClone by hand (cycle-safe)","/exams/interview/iv-hand-data#ex-hd-clone-write","code-completion",0],
  ["exercise","hd-flatten-write","interview","手写 flatten（depth 语义对齐原生 flat）","Write flatten by hand (depth behaves like the built-in flat)","/exams/interview/iv-hand-data#ex-hd-flatten-write","code-completion",0],
  ["exercise","hd-curry-write","interview","手写 curry（部分应用可复用）","Write curry by hand (partial applications stay reusable)","/exams/interview/iv-hand-data#ex-hd-curry-write","code-completion",0],
  ["exercise","hd-pall-write","interview","手写 Promise.all + allSettled","Write Promise.all and allSettled by hand","/exams/interview/iv-hand-async#ex-hd-pall-write","code-completion",0],
  ["exercise","hd-emitter-write","interview","手写 EventEmitter","Write an EventEmitter by hand","/exams/interview/iv-hand-async#ex-hd-emitter-write","code-completion",0],
  ["exercise","hd-lru-write","interview","手写 LRUCache（用 Map，不写链表）","Write an LRUCache by hand (use a Map, no linked list)","/exams/interview/iv-hand-async#ex-hd-lru-write","code-completion",0],
  ["exercise","iv-ts-utility-recog","interview","认出这个 mapped type 在干什么","Work out what this mapped type does","/exams/interview/iv-ts-utility#ex-iv-ts-utility-recog","recognition",0],
  ["exercise","iv-ts-generics-recog","interview","unknown 参数该怎么用起来","How to actually use an unknown parameter","/exams/interview/iv-ts-generics#ex-iv-ts-generics-recog","recognition",0],
  ["coding","hand-debounce","","手写 debounce（带 cancel）","Write debounce yourself (with cancel)","/code/hand-debounce","",15],
  ["coding","hand-throttle","","手写 throttle（leading + trailing）","Write throttle yourself (leading and trailing)","/code/hand-throttle","",20],
  ["coding","hand-deep-clone","","手写 deepClone（防循环）","Write deepClone yourself (handling cycles)","/code/hand-deep-clone","",25],
  ["coding","hand-flatten","","手写 flatten（depth 语义对齐原生）","Write flatten yourself (depth behaves like the built-in)","/code/hand-flatten","",15],
  ["coding","hand-curry","","手写 curry（部分应用可复用）","Write curry yourself (reusable partial application)","/code/hand-curry","",15],
  ["coding","hand-promise-all","","手写 Promise.all + allSettled","Write Promise.all and allSettled yourself","/code/hand-promise-all","",25],
  ["coding","hand-event-emitter","","手写 EventEmitter（on/off/once/emit）","Write EventEmitter yourself (on / off / once / emit)","/code/hand-event-emitter","",20],
  ["coding","hand-lru","","手写 LRUCache（用 Map 的插入序）","Write LRUCache yourself (using Map insertion order)","/code/hand-lru","",20],
  ["coding","tabs","","Tabs 组件（只用一个 state）","Tabs component (one piece of state only)","/code/tabs","",20],
  ["coding","star-rating","","星级评分（hover 预览 + 受控双模式）","Star rating (hover preview, controlled and uncontrolled)","/code/star-rating","",25],
  ["coding","dropdown","","Dropdown：点外面要关掉","Dropdown: close it on an outside click","/code/dropdown","",25],
  ["coding","use-local-storage","","写一个自定义 hook：useLocalStorage","Write a custom hook: useLocalStorage","/code/use-local-storage","",25],
  ["coding","player","","播放器（useRef 操作 DOM）","Media player (touching the DOM with useRef)","/code/player","",25],
  ["coding","kanban","","Kanban 看板：一次改两个数组","Kanban board: changing two arrays at once","/code/kanban","",40],
  ["coding","rtk-todo","","Redux Toolkit 版 Todo","Todo with Redux Toolkit","/code/rtk-todo","",40]
];

export const PLAN_MANIFEST: ManifestPlan[] = [
  {
    "id": "complete",
    "zh": "从零完整学习",
    "en": "Complete DrillLab",
    "outcomeZh": "从「npm install 做了什么」走到在空文件夹里重写三个项目，并把 105 道八股过一遍。",
    "outcomeEn": "From what npm install actually does, to rebuilding three projects in an empty folder, with all 105 questions covered.",
    "forZh": "刚开始接触 npm、React、GraphQL，想要一条完整的路。",
    "forEn": "New to npm, React and GraphQL, and wanting one complete route.",
    "minutes": 2536,
    "stages": [
      {
        "id": "f-learn",
        "phase": "learn",
        "zh": "地基：一个项目是怎么跑起来的",
        "en": "Foundations: how a project actually runs",
        "items": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8
        ]
      },
      {
        "id": "f-practice",
        "phase": "practice",
        "zh": "地基的课内练习",
        "en": "The Foundations exercises",
        "items": [
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19,
          20,
          21,
          22,
          23,
          24
        ]
      },
      {
        "id": "r-learn",
        "phase": "learn",
        "zh": "React 考试：课文",
        "en": "React exam: the lessons",
        "items": [
          25,
          26,
          27,
          28,
          29,
          30,
          31,
          32,
          33,
          34,
          35,
          36,
          37,
          38,
          39,
          40,
          41,
          42,
          43,
          44,
          45
        ]
      },
      {
        "id": "r-practice",
        "phase": "practice",
        "zh": "React 的课内练习",
        "en": "The React exercises",
        "items": [
          46,
          47,
          48,
          49,
          50,
          51,
          52,
          53,
          54,
          55,
          56,
          57,
          58,
          59,
          60,
          61,
          62,
          63,
          64,
          65,
          66,
          67,
          68,
          69,
          70,
          71,
          72,
          73,
          74,
          75,
          76,
          77,
          78,
          79,
          80,
          81,
          82,
          83,
          84,
          85,
          86,
          87,
          88,
          89,
          90,
          91,
          92,
          93,
          94,
          95,
          96,
          97,
          98,
          99
        ]
      },
      {
        "id": "r-code",
        "phase": "code",
        "zh": "React 的 Coding 题",
        "en": "The React coding problems",
        "items": [
          100,
          101,
          102,
          103,
          104,
          105,
          106
        ]
      },
      {
        "id": "r-rebuild",
        "phase": "rebuild",
        "zh": "React：空文件夹里重写",
        "en": "React: rebuild in an empty folder",
        "items": [
          107,
          108
        ]
      },
      {
        "id": "r-assess",
        "phase": "assess",
        "zh": "React 模拟考",
        "en": "The React mock exam",
        "items": [
          109
        ]
      },
      {
        "id": "g-learn",
        "phase": "learn",
        "zh": "Federation 考试：课文",
        "en": "Federation exam: the lessons",
        "items": [
          110,
          111,
          112,
          113,
          114,
          115,
          116,
          117,
          118,
          119,
          120,
          121,
          122,
          123,
          124,
          125,
          126
        ]
      },
      {
        "id": "g-practice",
        "phase": "practice",
        "zh": "Federation 的课内练习",
        "en": "The Federation exercises",
        "items": [
          127,
          128,
          129,
          130,
          131,
          132,
          133,
          134,
          135,
          136,
          137,
          138,
          139,
          140,
          141,
          142,
          143,
          144,
          145,
          146,
          147,
          148,
          149,
          150,
          151,
          152,
          153,
          154,
          155,
          156,
          157,
          158,
          159,
          160,
          161,
          162,
          163,
          164,
          165,
          166,
          167,
          168,
          169,
          170,
          171,
          172,
          173
        ]
      },
      {
        "id": "g-code",
        "phase": "code",
        "zh": "Federation 与 Spring 的 Coding 题",
        "en": "The Federation and Spring coding problems",
        "items": [
          174,
          175
        ]
      },
      {
        "id": "g-rebuild",
        "phase": "rebuild",
        "zh": "Federation：空文件夹里重写",
        "en": "Federation: rebuild in an empty folder",
        "items": [
          176,
          177
        ]
      },
      {
        "id": "g-assess",
        "phase": "assess",
        "zh": "Federation 模拟考",
        "en": "The Federation mock exam",
        "items": [
          178
        ]
      },
      {
        "id": "cb-learn",
        "phase": "learn",
        "zh": "Cab Booking：课文",
        "en": "Cab Booking: the lessons",
        "items": [
          179,
          180,
          181,
          182,
          183,
          184,
          185,
          186
        ]
      },
      {
        "id": "cb-practice",
        "phase": "practice",
        "zh": "Cab Booking 的课内练习",
        "en": "The Cab Booking exercises",
        "items": [
          187,
          188,
          189,
          190,
          191,
          192,
          193,
          194,
          195,
          196,
          197,
          198,
          199,
          200,
          201
        ]
      },
      {
        "id": "cb-code",
        "phase": "code",
        "zh": "Cab Booking 的 Coding 题",
        "en": "The Cab Booking coding problem",
        "items": [
          202
        ]
      },
      {
        "id": "cb-rebuild",
        "phase": "rebuild",
        "zh": "Cab Booking：空文件夹里重写",
        "en": "Cab Booking: rebuild in an empty folder",
        "items": [
          203
        ]
      },
      {
        "id": "iv-review",
        "phase": "review",
        "zh": "面试八股：105 道问答",
        "en": "Interview questions: all 105",
        "items": [
          204,
          205,
          206,
          207,
          208,
          209,
          210,
          211,
          212,
          213,
          214,
          215,
          216,
          217,
          218,
          219,
          220,
          221,
          222,
          223,
          224,
          225,
          226,
          227,
          228,
          229,
          230,
          231,
          232,
          233,
          234,
          235,
          236,
          237,
          238,
          239,
          240,
          241,
          242,
          243,
          244,
          245,
          246,
          247,
          248,
          249,
          250,
          251,
          252,
          253,
          254,
          255,
          256,
          257,
          258,
          259,
          260,
          261,
          262,
          263,
          264,
          265,
          266,
          267,
          268,
          269,
          270,
          271,
          272,
          273,
          274,
          275,
          276,
          277,
          278,
          279,
          280,
          281,
          282,
          283,
          284,
          285,
          286,
          287,
          288,
          289,
          290,
          291,
          292,
          293,
          294,
          295,
          296,
          297,
          298,
          299,
          300,
          301,
          302,
          303,
          304,
          305,
          306,
          307,
          308
        ]
      },
      {
        "id": "iv-learn",
        "phase": "learn",
        "zh": "手写题与组件题的讲解",
        "en": "The walkthroughs for the hand-written and component problems",
        "items": [
          309,
          310,
          311,
          312,
          313,
          314,
          315,
          316,
          317,
          318
        ]
      },
      {
        "id": "iv-practice",
        "phase": "practice",
        "zh": "面试那门课的练习",
        "en": "The exercises in the interview course",
        "items": [
          319,
          320,
          321,
          322,
          323,
          324,
          325,
          326,
          327,
          328,
          329,
          330,
          331,
          332,
          333,
          334
        ]
      },
      {
        "id": "iv-code",
        "phase": "code",
        "zh": "手写题与组件题",
        "en": "The hand-written and component problems",
        "items": [
          335,
          336,
          337,
          338,
          339,
          340,
          341,
          342,
          343,
          344,
          345,
          346,
          347,
          348,
          349
        ]
      }
    ]
  },
  {
    "id": "react-assessment",
    "zh": "React 考试准备",
    "en": "React Assessment",
    "outcomeZh": "在空文件夹里做完 Notes Manager 和并发任务调度器，并通过一套换了场景的模拟考。",
    "outcomeEn": "Build Notes Manager and the concurrent task runner in an empty folder, and pass a mock in a new scenario.",
    "forZh": "要考 React：组件、hooks、受控输入、列表、useEffect、Context。",
    "forEn": "Facing a React assessment: components, hooks, controlled inputs, lists, useEffect, Context.",
    "minutes": 912,
    "stages": [
      {
        "id": "prereq",
        "phase": "prereq",
        "zh": "前置：地基",
        "en": "Prerequisites: Foundations",
        "items": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8
        ]
      },
      {
        "id": "learn",
        "phase": "learn",
        "zh": "学：React 课文",
        "en": "Learn: the React lessons",
        "items": [
          25,
          26,
          27,
          28,
          29,
          30,
          31,
          32,
          33,
          34,
          35,
          36,
          37,
          38,
          39,
          40,
          41,
          42,
          43,
          44,
          45
        ]
      },
      {
        "id": "review",
        "phase": "review",
        "zh": "背：React 方向的八股",
        "en": "Review: the React questions",
        "items": [
          255,
          256,
          257,
          258,
          259,
          260,
          261,
          262,
          263,
          264,
          265,
          266,
          267,
          268,
          269,
          270,
          271,
          272,
          273,
          274,
          275,
          276,
          277,
          278,
          279,
          280,
          281,
          282,
          283,
          284,
          285,
          286,
          287,
          288,
          289,
          290
        ]
      },
      {
        "id": "practice",
        "phase": "practice",
        "zh": "练：React 的课内练习",
        "en": "Practice: the React exercises",
        "items": [
          46,
          47,
          48,
          49,
          50,
          51,
          52,
          53,
          54,
          55,
          56,
          57,
          58,
          59,
          60,
          61,
          62,
          63,
          64,
          65,
          66,
          67,
          68,
          69,
          70,
          71,
          72,
          73,
          74,
          75,
          76,
          77,
          78,
          79,
          80,
          81,
          82,
          83,
          84,
          85,
          86,
          87,
          88,
          89,
          90,
          91,
          92,
          93,
          94,
          95,
          96,
          97,
          98,
          99
        ]
      },
      {
        "id": "code",
        "phase": "code",
        "zh": "写：React 的 Coding 题",
        "en": "Code: the React coding problems",
        "items": [
          100,
          101,
          102,
          103,
          104,
          105,
          106
        ]
      },
      {
        "id": "rebuild",
        "phase": "rebuild",
        "zh": "空手做：从零重写",
        "en": "Rebuild: from an empty folder",
        "items": [
          107,
          108
        ]
      },
      {
        "id": "assess",
        "phase": "assess",
        "zh": "模拟考：Support Ticket Board",
        "en": "Assess: Support Ticket Board",
        "items": [
          109
        ]
      }
    ]
  },
  {
    "id": "federation-assessment",
    "zh": "GraphQL Federation 考试准备",
    "en": "GraphQL Federation Assessment",
    "outcomeZh": "自己搭一个 Apollo Federation subgraph 并让十个测试全过，再通过一套换了场景的模拟考。",
    "outcomeEn": "Build an Apollo Federation subgraph yourself with all ten tests passing, then pass a mock in a new scenario.",
    "forZh": "要考 GraphQL Federation：schema、resolver、entity、DataLoader，外加一个 Spring Boot 服务。",
    "forEn": "Facing a Federation assessment: schema, resolvers, entities, DataLoader, plus a Spring Boot service.",
    "minutes": 867,
    "stages": [
      {
        "id": "prereq",
        "phase": "prereq",
        "zh": "前置：地基",
        "en": "Prerequisites: Foundations",
        "items": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8
        ]
      },
      {
        "id": "learn",
        "phase": "learn",
        "zh": "学：Federation 课文",
        "en": "Learn: the Federation lessons",
        "items": [
          110,
          111,
          112,
          113,
          114,
          115,
          116,
          117,
          118,
          119,
          120,
          121,
          122,
          123,
          124,
          125,
          126
        ]
      },
      {
        "id": "review",
        "phase": "review",
        "zh": "背：Node、数据库、网络与安全",
        "en": "Review: Node, databases, networking and security",
        "items": [
          291,
          292,
          293,
          294,
          295,
          296,
          297,
          298,
          299,
          300,
          301,
          302
        ]
      },
      {
        "id": "practice",
        "phase": "practice",
        "zh": "练：Federation 的课内练习",
        "en": "Practice: the Federation exercises",
        "items": [
          127,
          128,
          129,
          130,
          131,
          132,
          133,
          134,
          135,
          136,
          137,
          138,
          139,
          140,
          141,
          142,
          143,
          144,
          145,
          146,
          147,
          148,
          149,
          150,
          151,
          152,
          153,
          154,
          155,
          156,
          157,
          158,
          159,
          160,
          161,
          162,
          163,
          164,
          165,
          166,
          167,
          168,
          169,
          170,
          171,
          172,
          173
        ]
      },
      {
        "id": "code",
        "phase": "code",
        "zh": "写：subgraph 与 Spring 控制器",
        "en": "Code: the subgraph and the Spring controller",
        "items": [
          174,
          175
        ]
      },
      {
        "id": "rebuild",
        "phase": "rebuild",
        "zh": "空手做：从零重写两道",
        "en": "Rebuild: both tasks from an empty folder",
        "items": [
          176,
          177
        ]
      },
      {
        "id": "assess",
        "phase": "assess",
        "zh": "模拟考：Book Reviews Subgraph",
        "en": "Assess: Book Reviews Subgraph",
        "items": [
          178
        ]
      }
    ]
  },
  {
    "id": "spring-controller",
    "zh": "Spring Boot 控制器准备",
    "en": "Spring Boot Controller",
    "outcomeZh": "在一个空的 Spring Initializr 骨架里写出六个 REST 端点，五个测试全过。",
    "outcomeEn": "Write six REST endpoints in an empty Spring Initializr skeleton, with all five tests passing.",
    "forZh": "只准备 Federation 考试里那道 Spring Boot 控制器题。",
    "forEn": "Preparing only for the Spring Boot controller task in the Federation assessment.",
    "minutes": 184,
    "stages": [
      {
        "id": "learn",
        "phase": "learn",
        "zh": "学：这道题要读懂的两节",
        "en": "Learn: the two lessons this task needs",
        "items": [
          122,
          123
        ]
      },
      {
        "id": "practice",
        "phase": "practice",
        "zh": "练：这两节的练习，加一个 Java Debug Lab",
        "en": "Practice: those lessons' exercises, plus one Java debug lab",
        "items": [
          158,
          159,
          160,
          161,
          162,
          163,
          164,
          171
        ]
      },
      {
        "id": "code",
        "phase": "code",
        "zh": "写：六个端点",
        "en": "Code: the six endpoints",
        "items": [
          175
        ]
      },
      {
        "id": "rebuild",
        "phase": "rebuild",
        "zh": "空手做：从零重写控制器",
        "en": "Rebuild: the controller from nothing",
        "items": [
          177
        ]
      }
    ]
  },
  {
    "id": "frontend-interview",
    "zh": "前端面试复习",
    "en": "Frontend Interview Review",
    "outcomeZh": "105 道问答用嘴答一遍，再把 15 道手写题和组件题写一遍。",
    "outcomeEn": "Answer all 105 questions out loud, then write the 15 hand-written and component problems.",
    "forZh": "下周有面试，要的是「说得出」加「当场写得出」。",
    "forEn": "An interview next week: you need to say it, and to write it on the spot.",
    "minutes": 557,
    "stages": [
      {
        "id": "rev-markup",
        "phase": "review",
        "zh": "背：HTML 与 CSS",
        "en": "Review: HTML and CSS",
        "items": [
          204,
          205,
          206,
          207,
          208,
          209,
          210,
          211,
          212,
          213,
          214,
          215,
          216
        ]
      },
      {
        "id": "rev-js",
        "phase": "review",
        "zh": "背：JavaScript 与 TypeScript",
        "en": "Review: JavaScript and TypeScript",
        "items": [
          217,
          218,
          219,
          220,
          221,
          222,
          223,
          224,
          225,
          226,
          227,
          228,
          229,
          230,
          231,
          232,
          233,
          234,
          235,
          236,
          237,
          238,
          239,
          240,
          241,
          242,
          243,
          244,
          245,
          246,
          247,
          248,
          249,
          250,
          251,
          252,
          253,
          254,
          303,
          304,
          305,
          306,
          307,
          308
        ]
      },
      {
        "id": "rev-react",
        "phase": "review",
        "zh": "背：React 与生态",
        "en": "Review: React and its ecosystem",
        "items": [
          255,
          256,
          257,
          258,
          259,
          260,
          261,
          262,
          263,
          264,
          265,
          266,
          267,
          268,
          269,
          270,
          271,
          272,
          273,
          274,
          275,
          276,
          277,
          278,
          279,
          280,
          281,
          282,
          283,
          284,
          285,
          286,
          287,
          288,
          289,
          290
        ]
      },
      {
        "id": "rev-backend",
        "phase": "review",
        "zh": "背：Node、数据库、网络与安全",
        "en": "Review: Node, databases, networking and security",
        "items": [
          291,
          292,
          293,
          294,
          295,
          296,
          297,
          298,
          299,
          300,
          301,
          302
        ]
      },
      {
        "id": "learn",
        "phase": "learn",
        "zh": "学：手写题与组件题的讲解",
        "en": "Learn: the walkthroughs",
        "items": [
          309,
          310,
          311,
          312,
          313,
          314,
          315,
          316
        ]
      },
      {
        "id": "practice",
        "phase": "practice",
        "zh": "练：这门课的练习",
        "en": "Practice: this course's exercises",
        "items": [
          319,
          320,
          321,
          322,
          323,
          324,
          325,
          326,
          327,
          328,
          329,
          330,
          331,
          332,
          333,
          334
        ]
      },
      {
        "id": "code-hand",
        "phase": "code",
        "zh": "写：手写题",
        "en": "Code: implement it yourself",
        "items": [
          335,
          336,
          337,
          338,
          339,
          340,
          341,
          342
        ]
      },
      {
        "id": "code-widgets",
        "phase": "code",
        "zh": "写：组件与状态管理题",
        "en": "Code: components and state management",
        "items": [
          343,
          344,
          345,
          346,
          347,
          348,
          349
        ]
      }
    ]
  },
  {
    "id": "cab-booking",
    "zh": "Cab Booking 完整练习",
    "en": "Cab Booking",
    "outcomeZh": "在空文件夹里搭出整个 Cab Booking 应用：Context 管全局状态，四个页面一个状态机，四个测试全过。",
    "outcomeEn": "Build the whole Cab Booking app in an empty folder: Context for global state, four pages on one state machine, all four tests passing.",
    "forZh": "要做那道用 Context 管全局状态的 React 应用题。",
    "forEn": "Facing the React task that holds global state in Context.",
    "minutes": 446,
    "stages": [
      {
        "id": "prereq-f",
        "phase": "prereq",
        "zh": "前置：地基",
        "en": "Prerequisites: Foundations",
        "items": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8
        ]
      },
      {
        "id": "prereq-r",
        "phase": "prereq",
        "zh": "前置：这道题用到的 React 那几节",
        "en": "Prerequisites: the React lessons this task leans on",
        "items": [
          25,
          26,
          27,
          30,
          43
        ]
      },
      {
        "id": "learn",
        "phase": "learn",
        "zh": "学：Cab Booking 课文",
        "en": "Learn: the Cab Booking lessons",
        "items": [
          179,
          180,
          181,
          182,
          183,
          184,
          185,
          186
        ]
      },
      {
        "id": "practice",
        "phase": "practice",
        "zh": "练：Cab Booking 的课内练习",
        "en": "Practice: the Cab Booking exercises",
        "items": [
          187,
          188,
          189,
          190,
          191,
          192,
          193,
          194,
          195,
          196,
          197,
          198,
          199,
          200,
          201
        ]
      },
      {
        "id": "code",
        "phase": "code",
        "zh": "写：Context 版 Cab Booking",
        "en": "Code: the Context version",
        "items": [
          202
        ]
      },
      {
        "id": "rebuild",
        "phase": "rebuild",
        "zh": "空手做：整个应用从零重写",
        "en": "Rebuild: the whole app from nothing",
        "items": [
          203
        ]
      }
    ]
  }
];
